version: 3

vars:
  GOOS: "{{default OS .GOOS}}"
  DC_DIR: "deployment/docker-compose"
  INFRA_DC_FILE: "{{.DC_DIR}}/infra.yml"


tasks:
  default:
    cmds:
      - task: test
  test:
    deps: [format]
    cmds:
      - "mvn clean verify"

  format:
    cmds:
      - "mvn spotless:apply"

  build:
    cmds:
      - "mvn verify"

  start_infra:
    cmds:
      - docker compose -f {{.INFRA_DC_FILE}} up -d


  stop_infra:
    cmds:
      - docker compose -f {{.INFRA_DC_FILE}} stop
      - docker compose -f {{.INFRA_DC_FILE}} rm -f

  restart_infra:
    cmds:
      - task: stop_infra
      - task: sleep
      - task: start_infra

  sleep:
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - sleep {{.DURATION}}

